let name = "<strong>Vill</strong>"
let name2 = "<strong># Ode to Vill: The Web Weaver </strong>"
let name3 = "<strong>## I. The Blank Canvas </strong>"
let name4 = "<strong>## II. The HTML Symphony </strong>"
let name5 = "<strong> ## III. The CSS Enchanter </strong>"
let name6 = "<strong> IV. The JavaScript Magician </strong>"
let name7 = "<strong>## V. The Debugging Sage </strong>"
let name8 = "<strong>## VI. The Responsive Voyager</strong>"
let name9 = "<strong>## VII. The SEO Whisperer</strong>"
let name10 = "<strong>## VIII. The Git Alchemist</strong>"
let name11 = "<strong>## IX. The Deployment Dreamer</strong>"
let name12 = "<strong>## X. The Web Developer's Anthem</strong>"

let _p1a = "<strong>realm</strong>"
let _p1b = "<strong>pixels</strong>"
let _p1c = "<strong>code</strong>"
let _p1d = "<strong>**web weaver **</strong>"
let _p1e = "<strong>pearls</strong>"

let _p2a = "<strong>**alchemist of the browser**</strong>"
let _p2b = "<strong>keyboard</strong>"
let _p2c = "<strong>wand</strong>"
let _p2d = "<strong>pages</strong>"
let _p2e = "<strong>Painting</strong>"

let _p3a = "<strong>fingers</strong>"
let _p3b = "<strong>keys</strong>"
let _p3c = "<strong>tags</strong>"
let _p3d = "<strong>HTML</strong>"
let _p3e = "<strong>symphonies</strong>"

let _p4a = "<strong>**CSS cloack**</strong>"
let _p4b = "<strong>Styling</strong>"
let _p4c = "<strong>Colors bloom, fonts sing</strong>"
let _p4d = "<strong>evoke</strong>"
let _p4e = "<strong>visual</strong>"

let _p5a = "<strong>magic</strong>"
let _p5b = "<strong>**Javascript spells**</strong>"
let _p5c = "<strong>will, Forms </strong>"
let _p5d = "<strong>animations propel</strong>"

let _p6a = "<strong>bugs</strong>"
let _p6b = "<strong>**debugging spectacles**</strong>"
let _p6c = "<strong>glitches</strong>"
let _p6d = "<strong>code's arc</strong>"
let _p6e = "<strong>tames</strong>"
let _p6f = "<strong>variables.</strong>"

let _p7a = "<strong>Across</strong>"
let _p7b = "<strong>devices</strong>"
let _p7c = "<strong>**responsive sea**,</strong>"
let _p7d = "<strong>guide</strong>"
let _p7e = "<strong>Adapting</strong>"
let _p7f = "<strong>fluidity.</strong>"

let _p8a = "<strong>labyrinth </strong>"
let _p8b = "<strong>**SEO whisperer**,</strong>"
let _p8c = "<strong>Meta tags,</strong>"
let _p8d = "<strong>wanderers.</strong>"

let _p9a = "<strong>mystical potion,</strong>"
let _p9b = "<strong>Git's</strong>"
let _p9c = "<strong>merge </strong>"
let _p9d = "<strong>repository </strong>"
let _p9e = "<strong>code </strong>"

let _p10a = "<strong>moon</strong>"
let _p10b = "<strong>world,</strong>"
let _p10c = "<strong>Deployments</strong>"
let _p10d = "<strong>website</strong>"
let _p10e = "<strong>unfurled</strong>"

let _p11a = "<strong>**web developer**,</strong>"
let _p11b = "<strong>pixels,</strong>"
let _p11c = "<strong>clicks,</strong>"
let _p11d = "<strong>binary</strong>"
let _p11e = "<strong>matrix</strong>"


document.getElementById("demo").innerHTML = name2 + "<br>" + " In the " + _p1a + " of ones and zeros " + "<br>" + "Where" + _p1b + " dance and " + _p1c + " unfurls, " + "<br>"
+ " There resides a silent sorcerer, " + "<br>" + " A " + _p1d + " with dreams and " + _p1e + "<br>" + "<br>" + name3 + "<br>" + name + " the " + _p2a + "<br>" + "Wields his " + _p2b + "and " + _p2c + "<br>" + "He conjures " + _p2d + " from thin air, " + "<br>" + _p2e + "landscapes with line so fond." + "<br>" + "<br>" + name4 + "<br>" + "His " + _p3a + " dance upon " + _p3b + "<br>" + "Crafting" + _p3c + " like musical notes, " + "<br>" + _p3d + " whispers secrets to the breeze, " + "<br>" + " As " + name + " orchestrates " + _p3e + " in quotes " + "<br>"
+ "<br>" + name5 + "<br>" + "Next, he dons his " + _p4a + "," + "<br>" + _p4b + " elements with flair and grace," + "<br>" + _p4c + "," + _p4d + "," + "<br>" + _p4e + " ballet in this digital space." + "<br>"
+ "<br>" + name6 + "<br>" + "But wait, the magic deepens still," + "<br>" + name + " summons " + _p5b + "," + "<br>" + _p5c + " validate, " + _p5d + " propel." + "<br>"
+ "<br>" + name7 + "<br>" + "Yet, " + _p6a + " creep in like shadows dark," + "<br>" + name + " dons his " + _p6b + "," + "<br>" + _p6c + " through the " + _p6d + "," + "<br>" + "He " + _p6e + " wild loops and elusive " + _p6f + "<br>"
+ "<br>" + name8 + "<br>" + _p7a + " screens, " + _p7b + " and " + _p7c + "," + _p7d + " his intentions," + "<br>" + _p7e + " layouts with " + _p7f + "." + "<br>"
+ "<br>" + name9 + "<br>" + "In the " + _p8a + " of search engines," + "<br>" + name + " becomes an " + _p8b + "," + "<br>" + _p8c + " keywords, backlink strings," + "<br>" + "He crafts pathways to digital wanderers." + "<br>"
+ "<br>" + name10 + "<br>" + _p9a + " control, a mystical potion," + "<br>" + name + " brews commits in " + _p9b + " cauldron," + "<br>" + "Branches fork, " + _p9c + " conflicts in motion," + "<br>" + "His " + _p9d + " a saga of " + _p9e + " reborn." + "<br>"
+ "<br>" + name11 + "<br>" + "And when the " + _p10a + " kisses the horizon," + "<br>" + name + " unfurls his creation to the " + _p10b + "," + "<br>" + _p10c + " like shooting stars, arisen," + "<br>" + "His " + _p10d + " sails, its sails unfurled." + "<br>"
+ "<br>" + name12 + "<br>" + "So here's to " + name + ", the " + _p11a + "," + "<br>" + "A poet of " + _p11b + ", a composer of " + _p11c + "," + "<br>" + "In the binary symphony, he's the reveler," + "<br>" + "Weaving dreams into the digital " + _p11d + "." + "<br>"
+ "<br>" + "<i>Rod, may your lines be bug-free," + "<br>" + "May your CSS always cascade gracefully," + "<br>" + "And may your JavaScript forever flow," + "<br>" + "As you navigate the web's eternal ebb and flow.</i>" + "<br>";
